import Image from "next/image";
import Link from "next/link";
import ProjectGallery from "@/components/projectgallery";

const images = [
  {
    src: "/image/IoT DashBoard.png",
    caption: "IoT telemetry dashboard",
  },
  {
    src: "/image/Alat IoT.jpeg",
    caption: "IoT device prototype",
  },

  {
    src: "/image/Rangkaian.png",
    caption: "System architecture",
  },
];

export default function IoTTelemetryPage() {
  return (
    <main className="min-h-screen bg-[#f5f4ef] text-[#171717]">
      {/* Header */}
      <section className="border-b border-black/10 px-6 pb-20 pt-32 lg:px-10">
        <div className="mx-auto max-w-7xl">
          <Link
            href="/#projects"
            className="text-xs uppercase tracking-[0.2em] text-black/40 transition-colors hover:text-black"
          >
            ← Back to Projects
          </Link>

          <div className="mt-16 grid gap-10 lg:grid-cols-[1.3fr_0.7fr]">
            <div>
              <p className="text-xs uppercase tracking-[0.25em] text-[#a62b2b]">
                01 / IoT / Web Application
              </p>

              <h1 className="mt-6 max-w-5xl text-5xl font-bold leading-[0.9] tracking-[-0.05em] md:text-7xl lg:text-8xl">
                IoT
                <br />
                TELEMETRY
                <br />
                SYSTEM
              </h1>
            </div>

            <div className="flex items-end">
              <p className="max-w-md text-sm leading-7 text-black/55">
                A system for transmitting and visualizing telemetry
                data from IoT devices through a web application.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Project Gallery */}
      <section className="border-b border-black/10 px-6 py-20 lg:px-10">
        <div className="mx-auto max-w-7xl">
          <ProjectGallery images={images} />
        </div>
      </section>

      {/* Overview */}
      <section className="border-b border-black/10 px-6 py-24 lg:px-10">
        <div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.7fr_1.3fr]">
          <div>
            <p className="text-xs uppercase tracking-[0.25em] text-black/40">
              02 / Overview
            </p>
          </div>

          <div>
            <h2 className="text-3xl font-semibold tracking-[-0.03em] md:text-5xl">
              Connecting IoT data with a web interface.
            </h2>

            <p className="mt-8 max-w-3xl text-sm leading-8 text-black/55">
              This project focuses on connecting telemetry data
              generated by an IoT device with a web application.
              The system receives data through an API and makes
              the information available for visualization and
              further processing.
            </p>
          </div>
        </div>
      </section>

      {/* Architecture */}
      <section className="border-b border-black/10 px-6 py-24 lg:px-10">
        <div className="mx-auto max-w-7xl">
          <p className="text-xs uppercase tracking-[0.25em] text-black/40">
            03 / System Architecture
          </p>

          <h2 className="mt-6 text-4xl font-bold tracking-[-0.04em] md:text-6xl">
            SYSTEM FLOW
          </h2>

          <div className="mt-16 grid gap-4 md:grid-cols-4">
            {[
              "IoT Device",
              "Telemetry API",
              "Backend",
              "Dashboard",
            ].map((item, index) => (
              <div
                key={item}
                className="border border-black/10 p-8"
              >
                <p className="text-xs text-black/30">
                  0{index + 1}
                </p>

                <p className="mt-6 text-sm font-medium">
                  {item}
                </p>

                {index < 3 && (
                  <p className="mt-4 text-[#a62b2b] md:hidden">
                    ↓
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Technologies */}
      <section className="border-b border-black/10 px-6 py-24 lg:px-10">
        <div className="mx-auto max-w-7xl">
          <p className="text-xs uppercase tracking-[0.25em] text-black/40">
            04 / Technologies
          </p>

          <div className="mt-10 flex flex-wrap gap-3">
            {[
              "Next.js",
              "TypeScript",
              "REST API",
              "IoT",
              "Node.js",
            ].map((technology) => (
              <span
                key={technology}
                className="border border-black/10 px-4 py-2 text-xs uppercase tracking-[0.1em] text-black/55"
              >
                {technology}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="px-6 py-10 lg:px-10">
        <div className="mx-auto flex max-w-7xl items-center justify-between">
          <p className="text-xs text-black/40">
            IoT Telemetry System
          </p>

          <Link
            href="/#projects"
            className="text-xs uppercase tracking-[0.15em] text-black/50 hover:text-black"
          >
            Back
          </Link>
        </div>
      </footer>
    </main>
  );
}